project:
  type: website
  output-dir: docs

website:
  title: "Alexia Nijgorodov Profile"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: Blog/index.qmd
        text: "Blogs"

format:
  html:
    theme:
      - quartz
      - brand
    css: styles.css
    toc: true



